### ISSUE TITLE
Create Figma design with feature list

### ISSUE THREAD

**Issue by kylelhk** [kylelhk/Pictionary#1]
Further to our 1st team meeting on 25 Mar 2024 (in which the project theme "Pictionary" was set), the preliminary frontend design of the following pages will be created on Figma, supplemented with a list of features for the respective page:

1.  **Login and Sign Up page** ("introductory" view), with game context and purpose (**Kyle**)
2. **Home page**, including the leaderboard and other game information (**Kyle**)
3.  **Game Setup** page ("create requests" view), including a Canvas for drawing (**Pritam**)
4.  **Game Hall** ("find requests" view) for searching and accepting word-guessing tasks (**Fritz**)
5. **Game** page for task taker to infer the target word from the drawing (**Trieu**)
6. **Game History / User Profile** page, including a history of games created by the user, previous gameplays with results, and games in progress (**Pritam**)

The Figma design and feature list should be done by our next meeting on 1 Apr 2024 for further discussion.

**Comment by trieuH** [comment]
Screen mockups created based on wireframes

https://www.figma.com/file/KAI7AXZfm5LcutST6VLD7Z/Prototype?type=design&mode=design&t=OToZAvb8YlaXZ6gy-0
