### ISSUE TITLE
Decide on project structure and organise files accordingly

### ISSUE THREAD

**Issue by trieuH** [kylelhk/Pictionary#7]
Currently, our project lacks a modular structure, which makes maintenance more difficult and our project less scalable. To enhance our codebase, we can consider adopting a more organised and modular project structure.

Refer to these resources:
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-a-better-application-structure
https://flask.palletsprojects.com/en/3.0.x/blueprints/

TO DO:
- [ ] Define project structure
- [ ] Reorganise existing files and directories into a new project structure
- [ ] Test to ensure all functionality is maintained after restructuring

**Comment by kylelhk** [comment]
As discussed on Teams today, the project structure now is actually quite simple:

1. A html and css for each page, an images folder, and those .py files, app.db, and setting stuffs which are essential components of a Flask app.
2. What we need to further add may just be some js files for each of the web page, and also some testing files under the test folder.
3. The backend and database stuffs should be mostly done by revising forms.py, models.py, routes.py, and directly in SQLite app (whose data will be stored in app.db).
4. The deliverables folder is required by the instruction for documenting our deliverables at different stages.
5. The migrations folder should be auto generated by running the 3 commands for initialising database as stated in the README.

These are also supported by a lab facilitator:
<img width="716" alt="image" src="https://github.com/kylelhk/Pictionary/assets/116782485/7e66e2bf-c89c-4afa-a689-b5beb3d15f46">
